### ISSUE TITLE
No op cljc support

### ISSUE THREAD

**Issue by dcostaras** [roosta/herb#12]
We tend to er on the side of keeping components CLJC as far as possible to facilitate testing front ends in CLJ. Would you be open to a PR that no ops (or something reasonable) in CLJ context?

**Comment by roosta** [comment]
Sure, I'm open to a PR.

Herb used to work in cljc, but I removed it for various reasons. Shouldn't be to tricky to setup a noop if that's all you need.

**Comment by dcostaras** [comment]
Great, thanks :)
