### ISSUE TITLE
Using selectors in Herb

### ISSUE THREAD

**Issue by alexdao3** [roosta/herb#3]
Hi there, thanks for your work on this library!

There's a section in the guide about using selectors, but that appears to be more geared towards defining some global styles. I'd like to use some combination of Garden's `>` and `descendant` selectors in a style definition and apply it to the component via the `<class` macro i.e. apply something like 

```
# requires
[garden.selectors :as g]
   [garden.core :refer [css]]

(garden/css [:div [(g/> :div) {:margin-bottom "24px"}]])
# "div div {\n  margin-bottom: 24px;\n}"
```

Is this supported?

**Comment by roosta** [comment]
Hello, thank you for using Herb :)  Currently it is not, it's something I've wanted too.  I'll see about adding support for this as soon as I can.

**Comment by roosta** [comment]
[\[herb/herb "0.7.3-SNAPSHOT"\] - Clojars](https://clojars.org/herb/versions/0.7.3-SNAPSHOT)
The latest SNAPSHOT version now contains first draft selectors meta data. See [changelog](https://github.com/roosta/herb/blob/master/CHANGELOG.md) and [examples.cljs](https://github.com/roosta/herb/blob/631bcc4080c582d0dae70af231d02693ac9c35d7/demo/herbdemo/examples.cljs#L29) for examples of usage. I'll make a new version of herb as soon as its proven stable, haven't had the time to fully test it yet.

**Comment by roosta** [comment]
Honestly I'm not that well versed in selectors in garden. Developing herb it was basically a non-issue. All feedback on this would be appreciated.

**Comment by roosta** [comment]
Pushed draft two fixing some issues with the previous implementation. Changed the metadata keyword to `:combinators` too, since that's what supported with this new meta. Be sure to pull down the latest `0.7.3-SNAPSHOT` for this new update.

**Comment by roosta** [comment]
Upgraded herb to version 0.8.0, this version contains the combinators syntax detailed in the [changelog](https://github.com/roosta/herb/blob/master/CHANGELOG.md) and on the [tutorial site](http://herb.roosta.sh/#selectors) under selectors. Closing this issue.
