### ISSUE TITLE
Multiple style rendering slow?

### ISSUE THREAD

**Issue by SuperRekursio** [roosta/herb#6]
Hi

The documentation says:

> The style is injected into the DOM when any one of Herb's macros are called.

Does this mean that every time I call one of Herb's macros during component rendering, it does an immediate synchronous DOM update? If so, doesn't it slow down component rendering? If a component render function does multiple Herb macro calls, then it causes multiple DOM update before the component has been rendered.

**Comment by roosta** [comment]
Yes, you are right, whenever either `<class`, or `<id` is called a synchronous update is done. In my experience it is unnoticeable, unless you do several hundred calls for a given component.

You can clone repo and run `lein fig:benchmark`, to get a breakdown of the speeds herb deliver, but on average if you call `<class` a 1000 times with unique arguments for each call it takes roughly 100ms for everything to render.

If speed is still a concern, there are other libraries that focus more on perf, you can check out [mscc](https://github.com/DogLooksGood/mcss), which was born partly from a discussion about herb and performance on [reddit](https://www.reddit.com/r/Clojure/comments/cehh8x/roostaherb_clojurescript_styling_library_using/).
