### ISSUE TITLE
Combine pseudo classes, pseudo elements and selectors

### ISSUE THREAD

**Issue by jalef** [roosta/herb#8]
Hello

How could someone:

1.  Combine pseudo classes and pseudo elements (or multiple pseudo classes and elements), something like: 
`div:last-child:after {...}`

2. Use :not, something like:
`div:not(:last-child):after {...}`

3. Use a pseudo-class (or element) for a selector, something like:
`div a :last-child:after {...}`

Thanks!

**Comment by roosta** [comment]
Hi there

You have a few options here, I'll try to detail all of them:

1. You can do that one like this:
```clojure
(defn one []
  ^{:pseudo {:last-child:after {:content "'>'"}}}
  {})

;; Defglobal lets you use gardens selector syntax
(defglobal global
  [:div:last-child:after {:content "'%'"}])
```

2. The pseudo element in herb can be a string, and must be so in some
   instances, but herb lets you use pretty much anything as a pseudo element.

```clojure
(defn two []
  ^{:pseudo {":not(:last-child):after" {:content "'#'"}}}
  {})

;; Defglobal

(defglobal global
  ["div:not(:last-child):after" {:content "'#'"}])
```

3. This one I could only do it using global styles

```clojure
(defglobal global
  [:div [:a [":last-child:after" {:content "'<'"}]]])
```
----

Herb wasn't originally designed to handle complicated selectors, and instead
relies more on adding classes when iterating through a collection or similar.
Garden is an option if you find herb lacking in this regard.

I hope this was helpful, and let me know if theres anything else I can do.

**Comment by jalef** [comment]
Thanks, this was very helpful!
